variables:
  GIT_SUBMODULE_STRATEGY: normal

debian10_build:
  image: debian:10
  script:
    - apt-get update
    - apt-get -y install build-essential autoconf automake libtool apache2 apache2-dev
    - autoreconf -i
    - CFLAGS="-Wall -Wpedantic -Werror" CXXFLAGS="-Wall -Wpedantic -Werror" ./configure
    - make
    - make check

debian9_build:
  image: debian:9
  script:
    - apt-get update
    - apt-get -y install build-essential autoconf automake libtool apache2 apache2-dev
    - autoreconf -i
    - CFLAGS="-Wall -Wpedantic -Werror" CXXFLAGS="-Wall -Wpedantic -Werror" ./configure
    - make
    - make check

centos6_build:
  image: centos:6
  script:
    - yum makecache fast
    - yum -y install autoconf automake libtool make gcc gcc-c++ httpd-devel which
    - autoreconf -i
    - CFLAGS="-Wall -pedantic -Werror" CXXFLAGS="-Wall -pedantic -Werror" ./configure
    - make
    - make CXXFLAGS="-Wall -Werror" check

centos7_build:
  image: centos:7
  script:
    - yum makecache fast
    - yum -y install autoconf automake libtool make gcc gcc-c++ httpd-devel which
    - autoreconf -i
    - CFLAGS="-std=gnu99 -Wall -Wpedantic -Werror" CXXFLAGS="-Wall -Wpedantic -Werror" ./configure
    - make
    - make check
